version: "3"
networks:
  znewbee:
    driver: bridge
services:
  app:
    image: znewbee/znewbee:0.7.0-alpha.78
    networks:
      - znewbee
    environment:
      - LOCAL_STORAGE_BASE_URL=http://localhost:13000/storage/uploads
    volumes:
      - ./storage:/app/znewbee/storage
    ports:
      - "13000:80"
