version: "3"
networks:
  znewbee:
    driver: bridge
services:
  app:
    image: znewbee/znewbee:0.7.0-alpha.78
    networks:
      - znewbee
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_DATABASE=znewbee
      - DB_USER=znewbee
      - DB_PASSWORD=znewbee
      - LOCAL_STORAGE_BASE_URL=http://localhost:13000/storage/uploads
    volumes:
      - ./storage:/app/znewbee/storage
    ports:
      - "13000:80"
    depends_on:
      - postgres
  postgres:
    image: postgres:10
    restart: always
    networks:
      - znewbee
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: znewbee
      POSTGRES_DB: znewbee
      POSTGRES_PASSWORD: znewbee
