version: "3"
networks:
  znewbee:
    driver: bridge
services:
  app:
    image: znewbee/znewbee:0.7.0-alpha.78
    networks:
      - znewbee
    depends_on:
      - mysql
    environment:
      - DB_DIALECT=mysql
      - DB_HOST=mysql
      - DB_DATABASE=znewbee
      - DB_USER=znewbee
      - DB_PASSWORD=znewbee
      - LOCAL_STORAGE_BASE_URL=http://localhost:13000/storage/uploads
    volumes:
      - ./storage:/app/znewbee/storage
    ports:
      - "13000:80"
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: znewbee
      MYSQL_USER: znewbee
      MYSQL_PASSWORD: znewbee
      MYSQL_ROOT_PASSWORD: znewbee
    restart: always
    networks:
      - znewbee
